import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

// import Header from '@/components/layout/header/Header'
// import Footer from '@/components/layout/footer/Footer'

import '@/assets/styles/globals.scss'
import '@/assets/styles/variables.scss'
import '@/assets/styles/media.scss'

const montserrat = Montserrat({ subsets: ['latin'], variable: '--var-montserrat' })

export const metadata: Metadata = {
  title: 'lorem ipsum dolor',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html>
      <body className={montserrat.variable}>
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}

export default RootLayout
